### ISSUE TITLE
Netbox v4

### ISSUE THREAD

**Issue by kprklg** [viroge/netbox-storage#4]
Good afternoon Compatible with Netbox v4?

**Comment by jaannnis** [comment]
with #3 it should at least start, haven't checked full functionality though.

**Comment by erichester76** [comment]
Im getting this with 4.1.1 :

netbox-1       | ImportError: cannot import name 'NestedClusterSerializer' from 'virtualization.api.serializers' (/opt/netbox/netbox/virtualization/api/serializers.py). Did you mean: 'ClusterSerializer'?

is that the valid name replacement name?

**Comment by viroge** [comment]
Yep, it supports both 4.0.x and 4.1.x now.
